=== kenewjr/kaziyami/schemas/index.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "AniyomiRepositoryIndex",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["name", "pkg", "apk", "lang", "code", "version", "nsfw", "sources"],
    "properties": {
      "name": {
        "type": "string"
      },
      "pkg": {
        "type": "string",
        "pattern": "^eu\\.kanade\\.tachiyomi\\.animeextension\\.[a-z]{2}\\.[a-z0-9]+$"
      },
      "apk": {
        "type": "string"
      },
      "lang": {
        "type": "string",
        "minLength": 2
      },
      "code": {
        "type": "integer",
        "minimum": 1
      },
      "version": {
        "type": "string"
      },
      "nsfw": {
        "type": "integer",
        "enum": [0, 1]
      },
      "hasReadme": {
        "type": "integer"
      },
      "hasChangelog": {
        "type": "integer"
      },
      "sources": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "required": ["name", "lang", "id", "baseUrl"],
          "properties": {
            "name": {
              "type": "string"
            },
            "lang": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "baseUrl": {
              "type": "string",
              "format": "uri"
            }
          }
        }
      }
    }
  }
}

=== kenewjr/kaziyami/repo/index.min.json
[{"name":"Nekopoi","pkg":"eu.kanade.tachiyomi.animeextension.id.nekopoi","apk":"aniyomi-id-nekopoi-v1.0.0.apk","lang":"id","code":1,"version":"1.0.0","nsfw":1,"hasReadme":0,"hasChangelog":0,"sources":[{"name":"Nekopoi","lang":"id","id":"7073589375897212735","baseUrl":"https://nekopoi.care"}]},{"name":"IndoHentai","pkg":"eu.kanade.tachiyomi.animeextension.id.indohentai","apk":"aniyomi-id-indohentai-v1.0.0.apk","lang":"id","code":1,"version":"1.0.0","nsfw":1,"hasReadme":0,"hasChangelog":0,"sources":[{"name":"IndoHentai","lang":"id","id":"7369497329911250289","baseUrl":"https://indohentai.net"}]},{"name":"Kuronime","pkg":"eu.kanade.tachiyomi.animeextension.id.kuronime","apk":"aniyomi-id-kuronime-v1.0.0.apk","lang":"id","code":1,"version":"1.0.0","nsfw":1,"hasReadme":0,"hasChangelog":0,"sources":[{"name":"Kuronime","lang":"id","id":"2083695115646974607","baseUrl":"https://kuronime.sbs"}]},{"name":"Hentaimama","pkg":"eu.kanade.tachiyomi.animeextension.en.hentaimama","apk":"aniyomi-en-hentaimama-v1.0.0.apk","lang":"en","code":1,"version":"1.0.0","nsfw":1,"hasReadme":0,"hasChangelog":0,"sources":[{"name":"Hentaimama","lang":"en","id":"8058423919997530503","baseUrl":"https://hentaimama.io"}]},{"name":"JAVSubbed","pkg":"eu.kanade.tachiyomi.animeextension.en.javsubbed","apk":"aniyomi-en-javsubbed-v1.0.0.apk","lang":"en","code":1,"version":"1.0.0","nsfw":1,"hasReadme":0,"hasChangelog":0,"sources":[{"name":"JAVSubbed","lang":"en","id":"9192959167101688940","baseUrl":"https://javsubbed.net"}]},{"name":"Hanime","pkg":"eu.kanade.tachiyomi.animeextension.en.hanime","apk":"aniyomi-en-hanime-v1.0.0.apk","lang":"en","code":1,"version":"1.0.0","nsfw":1,"hasReadme":0,"hasChangelog":0,"sources":[{"name":"Hanime","lang":"en","id":"2150907185602526076","baseUrl":"https://hanime.tv"}]}]

=== kenewjr/kaziyami/index.json
[
  {
    "name": "Kaziyami: Hanime",
    "pkg": "eu.kanade.tachiyomi.animeextension.en.hanime",
    "apk": "kaziyami-en.hanime-v14.1.apk",
    "lang": "en",
    "code": 1,
    "version": "14.1",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "Hanime",
        "lang": "en",
        "id": "2150907185602526076",
        "baseUrl": "https://hanime.tv"
      }
    ]
  },
  {
    "name": "Kaziyami: Hentaimama",
    "pkg": "eu.kanade.tachiyomi.animeextension.en.hentaimama",
    "apk": "kaziyami-en.hentaimama-v14.1.apk",
    "lang": "en",
    "code": 1,
    "version": "14.1",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "Hentaimama",
        "lang": "en",
        "id": "8058423919997530503",
        "baseUrl": "https://hentaimama.io"
      }
    ]
  },
  {
    "name": "Kaziyami: JAVSubbed",
    "pkg": "eu.kanade.tachiyomi.animeextension.en.javsubbed",
    "apk": "kaziyami-en.javsubbed-v14.1.apk",
    "lang": "en",
    "code": 1,
    "version": "14.1",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "JAVSubbed",
        "lang": "en",
        "id": "9192959167101688940",
        "baseUrl": "https://javsubbed.net"
      }
    ]
  },
  {
    "name": "Kaziyami: IndoHentai",
    "pkg": "eu.kanade.tachiyomi.animeextension.id.indohentai",
    "apk": "kaziyami-id.indohentai-v14.1.apk",
    "lang": "id",
    "code": 1,
    "version": "14.1",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "IndoHentai",
        "lang": "id",
        "id": "7369497329911250289",
        "baseUrl": "https://indohentai.net"
      }
    ]
  },
  {
    "name": "Kaziyami: Nekopoi",
    "pkg": "eu.kanade.tachiyomi.animeextension.id.nekopoi",
    "apk": "kaziyami-id.nekopoi-v14.1.apk",
    "lang": "id",
    "code": 1,
    "version": "14.1",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "Nekopoi",
        "lang": "id",
        "id": "7073589375897212735",
        "baseUrl": "https://nekopoi.care"
      }
    ]
  },
  {
    "name": "Kaziyami: NontonHentai",
    "pkg": "eu.kanade.tachiyomi.animeextension.id.nontonhentai",
    "apk": "kaziyami-id.nontonhentai-v14.1.apk",
    "lang": "id",
    "code": 1,
    "version": "14.1",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "NontonHentai",
        "lang": "id",
        "id": "7400791378172011716",
        "baseUrl": "https://nontonhentai.net"
      }
    ]
  }
]
